# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_axi_gpio_0_3/prio_axi_gpio_0_3.xci
# IP: The module: 'prio_axi_gpio_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_axi_gpio_0_3/prio_axi_gpio_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prio_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_axi_gpio_0_3/prio_axi_gpio_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prio_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_axi_gpio_0_3/prio_axi_gpio_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'prio_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_axi_gpio_0_3/prio_axi_gpio_0_3.xci
# IP: The module: 'prio_axi_gpio_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_axi_gpio_0_3/prio_axi_gpio_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prio_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_axi_gpio_0_3/prio_axi_gpio_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prio_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_axi_gpio_0_3/prio_axi_gpio_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'prio_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
