set_property PACKAGE_PIN M14 [get_ports {outputPort[3]}]
set_property PACKAGE_PIN N16 [get_ports {outputPort[2]}]
set_property PACKAGE_PIN P14 [get_ports {outputPort[1]}]
set_property PACKAGE_PIN R14 [get_ports {outputPort[0]}]
set_property PACKAGE_PIN D19 [get_ports {inputPort[0]}]
set_property PACKAGE_PIN D20 [get_ports {inputPort[1]}]
set_property PACKAGE_PIN L20 [get_ports {inputPort[2]}]
set_property PACKAGE_PIN L19 [get_ports {inputPort[3]}]

#set_property PACKAGE_PIN L19 [get_ports {inputPort_0[3]}]
#set_property PACKAGE_PIN L20 [get_ports {inputPort_0[2]}]
#set_property PACKAGE_PIN D20 [get_ports {inputPort_0[1]}]
#set_property PACKAGE_PIN D19 [get_ports {inputPort_0[0]}]
#set_property PACKAGE_PIN M14 [get_ports {outputPort_0[3]}]
#set_property PACKAGE_PIN N16 [get_ports {outputPort_0[2]}]
#set_property PACKAGE_PIN P14 [get_ports {outputPort_0[1]}]
#set_property PACKAGE_PIN R14 [get_ports {outputPort_0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {inputPort[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputPort[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputPort[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputPort[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputPort[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputPort[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputPort[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputPort[0]}]
