# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Convolution_Accel/Convolution_Accel.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Accel || ORIG_REF_NAME==Convolution_Accel} -quiet] -quiet

# IP: bd/Convolution_Accel/ip/Convolution_Accel_matrixAccTopDevice_0_0/Convolution_Accel_matrixAccTopDevice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Accel_matrixAccTopDevice_0_0 || ORIG_REF_NAME==Convolution_Accel_matrixAccTopDevice_0_0} -quiet] -quiet

# IP: bd/Convolution_Accel/ip/Convolution_Accel_processing_system7_0_0/Convolution_Accel_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Accel_processing_system7_0_0 || ORIG_REF_NAME==Convolution_Accel_processing_system7_0_0} -quiet] -quiet

# IP: bd/Convolution_Accel/ip/Convolution_Accel_xlslice_0_0/Convolution_Accel_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Accel_xlslice_0_0 || ORIG_REF_NAME==Convolution_Accel_xlslice_0_0} -quiet] -quiet

# IP: bd/Convolution_Accel/ip/Convolution_Accel_xlslice_0_1/Convolution_Accel_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Accel_xlslice_0_1 || ORIG_REF_NAME==Convolution_Accel_xlslice_0_1} -quiet] -quiet

# IP: bd/Convolution_Accel/ip/Convolution_Accel_xlslice_1_0/Convolution_Accel_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Accel_xlslice_1_0 || ORIG_REF_NAME==Convolution_Accel_xlslice_1_0} -quiet] -quiet

# IP: bd/Convolution_Accel/ip/Convolution_Accel_xlconcat_0_0/Convolution_Accel_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Accel_xlconcat_0_0 || ORIG_REF_NAME==Convolution_Accel_xlconcat_0_0} -quiet] -quiet

# XDC: bd/Convolution_Accel/Convolution_Accel_ooc.xdc
