# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects_Testing/PYNQ-HelloWorld-master/PYNQ-HelloWorld-master/boards/Pynq-Z2/resizer/resizer/resizer.srcs/sources_1/bd/resizer/ip/resizer_xbar_2/resizer_xbar_2.xci
# IP: The module: 'resizer_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects_Testing/PYNQ-HelloWorld-master/PYNQ-HelloWorld-master/boards/Pynq-Z2/resizer/resizer/resizer.srcs/sources_1/bd/resizer/ip/resizer_xbar_2/resizer_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'resizer_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects_Testing/PYNQ-HelloWorld-master/PYNQ-HelloWorld-master/boards/Pynq-Z2/resizer/resizer/resizer.srcs/sources_1/bd/resizer/ip/resizer_xbar_2/resizer_xbar_2.xci
# IP: The module: 'resizer_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects_Testing/PYNQ-HelloWorld-master/PYNQ-HelloWorld-master/boards/Pynq-Z2/resizer/resizer/resizer.srcs/sources_1/bd/resizer/ip/resizer_xbar_2/resizer_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'resizer_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
