@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Aug 14 18:14:40 -0500 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim aFIFO_tb_func_impl -key {Post-Implementation:sim_1:Functional:aFIFO_tb} -tclbatch aFIFO_tb.tcl -protoinst "protoinst_files/fifo.protoinst" -protoinst "protoinst_files/Convolution_Accel.protoinst" -log simulate.log"
call xsim  aFIFO_tb_func_impl -key {Post-Implementation:sim_1:Functional:aFIFO_tb} -tclbatch aFIFO_tb.tcl -protoinst "protoinst_files/fifo.protoinst" -protoinst "protoinst_files/Convolution_Accel.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
