# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config  -id {VRFC 10-2989}  -string {{ERROR: [VRFC 10-2989] 'break' is not declared [C:/Users/monke/Documents/GitHub/ReconHardware/PynqSoftware/Sources/Adder/adderFloat.v:60]}}  -suppress 
set_msg_config  -id {XSIM 43-3322}  -string {{ERROR: [XSIM 43-3322] Static elaboration of top level Verilog design unit(s) in library work failed.}}  -suppress 

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param chipscope.maxJobs 2
  reset_param project.defaultXPMLibraries 
  open_checkpoint C:/Users/monke/Documents/GitHub/ReconHardware/PynqSoftware/Projects/dynamicMatrixAccel/dynamicMatrixAccel.runs/impl_1/matrixAccelerator.dcp
  set_property webtalk.parent_dir C:/Users/monke/Documents/GitHub/ReconHardware/PynqSoftware/Projects/dynamicMatrixAccel/dynamicMatrixAccel.cache/wt [current_project]
  set_property parent.project_path C:/Users/monke/Documents/GitHub/ReconHardware/PynqSoftware/Projects/dynamicMatrixAccel/dynamicMatrixAccel.xpr [current_project]
  set_property ip_output_repo C:/Users/monke/Documents/GitHub/ReconHardware/PynqSoftware/Projects/dynamicMatrixAccel/dynamicMatrixAccel.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force matrixAccelerator_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file matrixAccelerator_drc_opted.rpt -pb matrixAccelerator_drc_opted.pb -rpx matrixAccelerator_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force matrixAccelerator_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file matrixAccelerator_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file matrixAccelerator_utilization_placed.rpt -pb matrixAccelerator_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file matrixAccelerator_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step phys_opt_design
set ACTIVE_STEP phys_opt_design
set rc [catch {
  create_msg_db phys_opt_design.pb
  phys_opt_design 
  write_checkpoint -force matrixAccelerator_physopt.dcp
  close_msg_db -file phys_opt_design.pb
} RESULT]
if {$rc} {
  step_failed phys_opt_design
  return -code error $RESULT
} else {
  end_step phys_opt_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force matrixAccelerator_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file matrixAccelerator_drc_routed.rpt -pb matrixAccelerator_drc_routed.pb -rpx matrixAccelerator_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file matrixAccelerator_methodology_drc_routed.rpt -pb matrixAccelerator_methodology_drc_routed.pb -rpx matrixAccelerator_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file matrixAccelerator_power_routed.rpt -pb matrixAccelerator_power_summary_routed.pb -rpx matrixAccelerator_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file matrixAccelerator_route_status.rpt -pb matrixAccelerator_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file matrixAccelerator_timing_summary_routed.rpt -pb matrixAccelerator_timing_summary_routed.pb -rpx matrixAccelerator_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file matrixAccelerator_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file matrixAccelerator_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file matrixAccelerator_bus_skew_routed.rpt -pb matrixAccelerator_bus_skew_routed.pb -rpx matrixAccelerator_bus_skew_routed.rpx"
  write_checkpoint -force -cell finalAdder finalAdder_adderFloat_routed.dcp
  write_checkpoint -force -cell genblk3[0].inputMulti genblk3_0_.inputMulti_Float_routed.dcp
  write_checkpoint -force -cell genblk3[1].inputMulti genblk3_1_.inputMulti_Float_routed.dcp
  write_checkpoint -force -cell genblk3[2].inputMulti genblk3_2_.inputMulti_Float_routed.dcp
  write_checkpoint -force -cell genblk4[0].outputAdder genblk4_0_.outputAdder_adderFloat_routed.dcp
  write_checkpoint -force -cell genblk4[1].outputAdder genblk4_1_.outputAdder_adderFloat_routed.dcp
  write_checkpoint -force -cell genblk4[2].outputAdder genblk4_2_.outputAdder_adderFloat_routed.dcp
  update_design -cell finalAdder -black_box
  update_design -cell genblk3[0].inputMulti -black_box
  update_design -cell genblk3[1].inputMulti -black_box
  update_design -cell genblk3[2].inputMulti -black_box
  update_design -cell genblk4[0].outputAdder -black_box
  update_design -cell genblk4[1].outputAdder -black_box
  update_design -cell genblk4[2].outputAdder -black_box
  lock_design -level routing
  write_checkpoint -force matrixAccelerator_routed_bb.dcp
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force matrixAccelerator_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

