# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test.xdc

# Block Designs: bd/PR_LED_des/PR_LED_des.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PR_LED_des || ORIG_REF_NAME==PR_LED_des} -quiet] -quiet

# IP: bd/PR_LED_des/ip/PR_LED_des_processing_system7_0_0/PR_LED_des_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PR_LED_des_processing_system7_0_0 || ORIG_REF_NAME==PR_LED_des_processing_system7_0_0} -quiet] -quiet

# IP: bd/PR_LED_des/ip/PR_LED_des_axi_gpio_0_0/PR_LED_des_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PR_LED_des_axi_gpio_0_0 || ORIG_REF_NAME==PR_LED_des_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PR_LED_des/ip/PR_LED_des_ps7_0_axi_periph_0/PR_LED_des_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PR_LED_des_ps7_0_axi_periph_0 || ORIG_REF_NAME==PR_LED_des_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PR_LED_des/ip/PR_LED_des_rst_ps7_0_100M_0/PR_LED_des_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PR_LED_des_rst_ps7_0_100M_0 || ORIG_REF_NAME==PR_LED_des_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/PR_LED_des/ip/PR_LED_des_auto_pc_0/PR_LED_des_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PR_LED_des_auto_pc_0 || ORIG_REF_NAME==PR_LED_des_auto_pc_0} -quiet] -quiet

# XDC: bd/PR_LED_des/PR_LED_des_ooc.xdc
