set_property IOSTANDARD LVCMOS33 [get_ports {led_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_n[0]}]
set_property PACKAGE_PIN M14 [get_ports {led_n[3]}]
set_property PACKAGE_PIN N16 [get_ports {led_n[2]}]
set_property PACKAGE_PIN P14 [get_ports {led_n[1]}]
set_property PACKAGE_PIN R14 [get_ports {led_n[0]}]
