
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_0_DEVICE_ID,
		XPAR_AXI_GPIO_0_BASEADDR,
		XPAR_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_0_IS_DUAL
	},
	{
		XPAR_BS_MONITOR_GPIO_1_DEVICE_ID,
		XPAR_BS_MONITOR_GPIO_1_BASEADDR,
		XPAR_BS_MONITOR_GPIO_1_INTERRUPT_PRESENT,
		XPAR_BS_MONITOR_GPIO_1_IS_DUAL
	},
	{
		XPAR_DFX_RST_GPIO_2_DEVICE_ID,
		XPAR_DFX_RST_GPIO_2_BASEADDR,
		XPAR_DFX_RST_GPIO_2_INTERRUPT_PRESENT,
		XPAR_DFX_RST_GPIO_2_IS_DUAL
	},
	{
		XPAR_SHUDOWN_ACK_GPIO_1_DEVICE_ID,
		XPAR_SHUDOWN_ACK_GPIO_1_BASEADDR,
		XPAR_SHUDOWN_ACK_GPIO_1_INTERRUPT_PRESENT,
		XPAR_SHUDOWN_ACK_GPIO_1_IS_DUAL
	}
};


