# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/monke/Downloads/imageFilterIP-master/imageFilterIP-master/inverter/inverter.srcs/sources_1/bd/dmaSystem/ip/dmaSystem_xbar_2/dmaSystem_xbar_2.xci
# IP: The module: 'dmaSystem_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/monke/Downloads/imageFilterIP-master/imageFilterIP-master/inverter/inverter.srcs/sources_1/bd/dmaSystem/ip/dmaSystem_xbar_2/dmaSystem_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaSystem_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/monke/Downloads/imageFilterIP-master/imageFilterIP-master/inverter/inverter.srcs/sources_1/bd/dmaSystem/ip/dmaSystem_xbar_2/dmaSystem_xbar_2.xci
# IP: The module: 'dmaSystem_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/monke/Downloads/imageFilterIP-master/imageFilterIP-master/inverter/inverter.srcs/sources_1/bd/dmaSystem/ip/dmaSystem_xbar_2/dmaSystem_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaSystem_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
