set_property PACKAGE_PIN R14 [get_ports {flatOutput[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[0]}]

set_property PACKAGE_PIN P14 [get_ports {flatOutput[1]}]
set_property PACKAGE_PIN N16 [get_ports {flatOutput[2]}]
set_property PACKAGE_PIN M14 [get_ports {flatOutput[3]}]
set_property PACKAGE_PIN L15 [get_ports {flatOutput[4]}]
set_property PACKAGE_PIN N15 [get_ports {flatOutput[5]}]
set_property PACKAGE_PIN G17 [get_ports {flatOutput[6]}]
set_property PACKAGE_PIN G14 [get_ports {flatOutput[7]}]
