# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AXI_Convolution/AXI_Convolution.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Convolution || ORIG_REF_NAME==AXI_Convolution} -quiet] -quiet

# IP: bd/AXI_Convolution/ip/AXI_Convolution_processing_system7_0_0/AXI_Convolution_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Convolution_processing_system7_0_0 || ORIG_REF_NAME==AXI_Convolution_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_Convolution/ip/AXI_Convolution_axi_dma_0_0/AXI_Convolution_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Convolution_axi_dma_0_0 || ORIG_REF_NAME==AXI_Convolution_axi_dma_0_0} -quiet] -quiet

# IP: bd/AXI_Convolution/ip/AXI_Convolution_xbar_0/AXI_Convolution_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Convolution_xbar_0 || ORIG_REF_NAME==AXI_Convolution_xbar_0} -quiet] -quiet

# IP: bd/AXI_Convolution/ip/AXI_Convolution_ps7_0_axi_periph_0/AXI_Convolution_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Convolution_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_Convolution_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_Convolution/ip/AXI_Convolution_rst_ps7_0_50M_0/AXI_Convolution_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Convolution_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_Convolution_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/AXI_Convolution/ip/AXI_Convolution_AXI_Convolution_Cont_0_0/AXI_Convolution_AXI_Convolution_Cont_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Convolution_AXI_Convolution_Cont_0_0 || ORIG_REF_NAME==AXI_Convolution_AXI_Convolution_Cont_0_0} -quiet] -quiet

# IP: bd/AXI_Convolution/ip/AXI_Convolution_axi_fifo_mm_s_0_0/AXI_Convolution_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Convolution_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==AXI_Convolution_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/AXI_Convolution/ip/AXI_Convolution_xlconcat_0_0/AXI_Convolution_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Convolution_xlconcat_0_0 || ORIG_REF_NAME==AXI_Convolution_xlconcat_0_0} -quiet] -quiet

# IP: bd/AXI_Convolution/ip/AXI_Convolution_auto_pc_0/AXI_Convolution_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Convolution_auto_pc_0 || ORIG_REF_NAME==AXI_Convolution_auto_pc_0} -quiet] -quiet

# Block Designs: bd/processor/processor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor || ORIG_REF_NAME==processor} -quiet] -quiet

# IP: bd/processor/ip/processor_processing_system7_0_0/processor_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_processing_system7_0_0 || ORIG_REF_NAME==processor_processing_system7_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_proc_sys_reset_0_0/processor_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_proc_sys_reset_0_0 || ORIG_REF_NAME==processor_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_interconnect_0_0/processor_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_interconnect_0_0 || ORIG_REF_NAME==processor_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_0_0/processor_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_0_0 || ORIG_REF_NAME==processor_axi_gpio_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_0_1/processor_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_0_1 || ORIG_REF_NAME==processor_axi_gpio_0_1} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_1_0/processor_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_1_0 || ORIG_REF_NAME==processor_axi_gpio_1_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_2_0/processor_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_2_0 || ORIG_REF_NAME==processor_axi_gpio_2_0} -quiet] -quiet

# IP: bd/processor/ip/processor_clk_wiz_0_0/processor_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_clk_wiz_0_0 || ORIG_REF_NAME==processor_clk_wiz_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_3_0/processor_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_3_0 || ORIG_REF_NAME==processor_axi_gpio_3_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_4_0/processor_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_4_0 || ORIG_REF_NAME==processor_axi_gpio_4_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_5_0/processor_axi_gpio_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_5_0 || ORIG_REF_NAME==processor_axi_gpio_5_0} -quiet] -quiet

# IP: bd/processor/ip/processor_xbar_0/processor_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_xbar_0 || ORIG_REF_NAME==processor_xbar_0} -quiet] -quiet

# IP: bd/processor/ip/processor_auto_pc_0/processor_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_auto_pc_0 || ORIG_REF_NAME==processor_auto_pc_0} -quiet] -quiet

# Block Designs: bd/testing_FIFO/testing_FIFO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testing_FIFO || ORIG_REF_NAME==testing_FIFO} -quiet] -quiet

# IP: bd/testing_FIFO/ip/testing_FIFO_axi_dma_0_0/testing_FIFO_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testing_FIFO_axi_dma_0_0 || ORIG_REF_NAME==testing_FIFO_axi_dma_0_0} -quiet] -quiet

# IP: bd/testing_FIFO/ip/testing_FIFO_axi_fifo_mm_s_0_0/testing_FIFO_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testing_FIFO_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==testing_FIFO_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/testing_FIFO/ip/testing_FIFO_processing_system7_0_0/testing_FIFO_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testing_FIFO_processing_system7_0_0 || ORIG_REF_NAME==testing_FIFO_processing_system7_0_0} -quiet] -quiet

# IP: bd/testing_FIFO/ip/testing_FIFO_xbar_0/testing_FIFO_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testing_FIFO_xbar_0 || ORIG_REF_NAME==testing_FIFO_xbar_0} -quiet] -quiet

# IP: bd/testing_FIFO/ip/testing_FIFO_ps7_0_axi_periph_0/testing_FIFO_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testing_FIFO_ps7_0_axi_periph_0 || ORIG_REF_NAME==testing_FIFO_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/testing_FIFO/ip/testing_FIFO_rst_ps7_0_50M_0/testing_FIFO_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testing_FIFO_rst_ps7_0_50M_0 || ORIG_REF_NAME==testing_FIFO_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/testing_FIFO/ip/testing_FIFO_xlconcat_0_0/testing_FIFO_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testing_FIFO_xlconcat_0_0 || ORIG_REF_NAME==testing_FIFO_xlconcat_0_0} -quiet] -quiet

# IP: bd/testing_FIFO/ip/testing_FIFO_auto_pc_2/testing_FIFO_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testing_FIFO_auto_pc_2 || ORIG_REF_NAME==testing_FIFO_auto_pc_2} -quiet] -quiet

# IP: bd/testing_FIFO/ip/testing_FIFO_auto_pc_0/testing_FIFO_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testing_FIFO_auto_pc_0 || ORIG_REF_NAME==testing_FIFO_auto_pc_0} -quiet] -quiet

# IP: bd/testing_FIFO/ip/testing_FIFO_auto_pc_1/testing_FIFO_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testing_FIFO_auto_pc_1 || ORIG_REF_NAME==testing_FIFO_auto_pc_1} -quiet] -quiet

# XDC: bd/AXI_Convolution/AXI_Convolution_ooc.xdc

# XDC: bd/processor/processor_ooc.xdc

# XDC: bd/testing_FIFO/testing_FIFO_ooc.xdc
