# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/processor/processor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor || ORIG_REF_NAME==processor} -quiet] -quiet

# IP: bd/processor/ip/processor_processing_system7_0_0/processor_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_processing_system7_0_0 || ORIG_REF_NAME==processor_processing_system7_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_proc_sys_reset_0_0/processor_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_proc_sys_reset_0_0 || ORIG_REF_NAME==processor_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_interconnect_0_0/processor_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_interconnect_0_0 || ORIG_REF_NAME==processor_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_0_0/processor_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_0_0 || ORIG_REF_NAME==processor_axi_gpio_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_0_1/processor_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_0_1 || ORIG_REF_NAME==processor_axi_gpio_0_1} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_1_0/processor_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_1_0 || ORIG_REF_NAME==processor_axi_gpio_1_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_2_0/processor_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_2_0 || ORIG_REF_NAME==processor_axi_gpio_2_0} -quiet] -quiet

# IP: bd/processor/ip/processor_clk_wiz_0_0/processor_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_clk_wiz_0_0 || ORIG_REF_NAME==processor_clk_wiz_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_3_0/processor_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_3_0 || ORIG_REF_NAME==processor_axi_gpio_3_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_4_0/processor_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_4_0 || ORIG_REF_NAME==processor_axi_gpio_4_0} -quiet] -quiet

# IP: bd/processor/ip/processor_axi_gpio_5_0/processor_axi_gpio_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_5_0 || ORIG_REF_NAME==processor_axi_gpio_5_0} -quiet] -quiet

# IP: bd/processor/ip/processor_xbar_0/processor_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_xbar_0 || ORIG_REF_NAME==processor_xbar_0} -quiet] -quiet

# IP: bd/processor/ip/processor_auto_pc_0/processor_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_auto_pc_0 || ORIG_REF_NAME==processor_auto_pc_0} -quiet] -quiet

# Block Designs: bd/Convolution_Controller/Convolution_Controller.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller || ORIG_REF_NAME==Convolution_Controller} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_processing_system7_0_0/Convolution_Controller_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_processing_system7_0_0 || ORIG_REF_NAME==Convolution_Controller_processing_system7_0_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_axi_dma_0_0/Convolution_Controller_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_axi_dma_0_0 || ORIG_REF_NAME==Convolution_Controller_axi_dma_0_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_xbar_0/Convolution_Controller_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_xbar_0 || ORIG_REF_NAME==Convolution_Controller_xbar_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_ps7_0_axi_periph_0/Convolution_Controller_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_ps7_0_axi_periph_0 || ORIG_REF_NAME==Convolution_Controller_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_rst_ps7_0_100M_0/Convolution_Controller_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_rst_ps7_0_100M_0 || ORIG_REF_NAME==Convolution_Controller_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_xbar_2/Convolution_Controller_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_xbar_2 || ORIG_REF_NAME==Convolution_Controller_xbar_2} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_axi_mem_intercon_1/Convolution_Controller_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_axi_mem_intercon_1 || ORIG_REF_NAME==Convolution_Controller_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_Convolution_Controll_0_1/Convolution_Controller_Convolution_Controll_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_Convolution_Controll_0_1 || ORIG_REF_NAME==Convolution_Controller_Convolution_Controll_0_1} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_auto_pc_0/Convolution_Controller_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_pc_0 || ORIG_REF_NAME==Convolution_Controller_auto_pc_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_s00_mmu_0/Convolution_Controller_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_s00_mmu_0 || ORIG_REF_NAME==Convolution_Controller_s00_mmu_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_auto_us_0/Convolution_Controller_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_us_0 || ORIG_REF_NAME==Convolution_Controller_auto_us_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_auto_us_1/Convolution_Controller_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_us_1 || ORIG_REF_NAME==Convolution_Controller_auto_us_1} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_auto_pc_1/Convolution_Controller_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_pc_1 || ORIG_REF_NAME==Convolution_Controller_auto_pc_1} -quiet] -quiet

# XDC: bd/processor/processor_ooc.xdc

# XDC: bd/Convolution_Controller/Convolution_Controller_ooc.xdc
