@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Aug 21 01:32:44 -0500 2019
REM SW Build 2580384 on Sat Jun 29 08:12:21 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim process_mod_tb_behav -key {Behavioral:sim_1:Functional:process_mod_tb} -tclbatch process_mod_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view D:/Adam/Documents/Vivado_Projects/development20180819/development20180819.srcs/sim_1/imports/20180818development4/interface_test_mod_tb_behav1.wcfg -log simulate.log"
call xsim  process_mod_tb_behav -key {Behavioral:sim_1:Functional:process_mod_tb} -tclbatch process_mod_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view D:/Adam/Documents/Vivado_Projects/development20180819/development20180819.srcs/sim_1/imports/20180818development4/interface_test_mod_tb_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
