set_property PACKAGE_PIN K9 [get_ports Vp_Vn_0_v_p]
set_property PACKAGE_PIN R14 [get_ports {leds_0[0]}]
set_property PACKAGE_PIN P14 [get_ports {leds_0[1]}]
set_property PACKAGE_PIN N16 [get_ports {leds_0[2]}]
set_property PACKAGE_PIN M14 [get_ports {leds_0[3]}]
set_property PACKAGE_PIN D19 [get_ports convst_in_0]

set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports convst_in_0]
set_property MARK_DEBUG true [get_nets Vp_Vn_0_v_p_IBUF]
set_property MARK_DEBUG true [get_nets Vp_Vn_0_v_n_IBUF]
set_property MARK_DEBUG true [get_nets convst_in_0_IBUF]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[10]}]
set_property MARK_DEBUG true [get_nets design_1_i/audio_interpreter_0_t_ready]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/xadc_wiz_0_m_axis_tdata[12]}]
set_property MARK_DEBUG true [get_nets design_1_i/xadc_wiz_0_m_axis_tvalid]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/xadc_wiz_0_m_axis_tdata[0]} {design_1_i/xadc_wiz_0_m_axis_tdata[1]} {design_1_i/xadc_wiz_0_m_axis_tdata[2]} {design_1_i/xadc_wiz_0_m_axis_tdata[3]} {design_1_i/xadc_wiz_0_m_axis_tdata[4]} {design_1_i/xadc_wiz_0_m_axis_tdata[5]} {design_1_i/xadc_wiz_0_m_axis_tdata[6]} {design_1_i/xadc_wiz_0_m_axis_tdata[7]} {design_1_i/xadc_wiz_0_m_axis_tdata[8]} {design_1_i/xadc_wiz_0_m_axis_tdata[9]} {design_1_i/xadc_wiz_0_m_axis_tdata[10]} {design_1_i/xadc_wiz_0_m_axis_tdata[11]} {design_1_i/xadc_wiz_0_m_axis_tdata[12]} {design_1_i/xadc_wiz_0_m_axis_tdata[13]} {design_1_i/xadc_wiz_0_m_axis_tdata[14]} {design_1_i/xadc_wiz_0_m_axis_tdata[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list convst_in_0_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list Vp_Vn_0_v_n_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list Vp_Vn_0_v_p_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/xadc_wiz_0_m_axis_tvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
