# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/GitHub/ReconHardware/FPGA_Files/Projects/Convolution_Accelerator/Convolution_Accelerator.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_1_1/design_2_axi_gpio_1_1.xci
# IP: The module: 'design_2_axi_gpio_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/Convolution_Accelerator/Convolution_Accelerator.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_1_1/design_2_axi_gpio_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/Convolution_Accelerator/Convolution_Accelerator.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_1_1/design_2_axi_gpio_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/Convolution_Accelerator/Convolution_Accelerator.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_1_1/design_2_axi_gpio_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/GitHub/ReconHardware/FPGA_Files/Projects/Convolution_Accelerator/Convolution_Accelerator.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_1_1/design_2_axi_gpio_1_1.xci
# IP: The module: 'design_2_axi_gpio_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/Convolution_Accelerator/Convolution_Accelerator.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_1_1/design_2_axi_gpio_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/Convolution_Accelerator/Convolution_Accelerator.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_1_1/design_2_axi_gpio_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/Convolution_Accelerator/Convolution_Accelerator.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_1_1/design_2_axi_gpio_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
