# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}


start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_param chipscope.maxJobs 2
  pr_verify -full_check -initial C:/GitHub/ReconHardware/PynqSoftware/Projects/Convolution_Accelerator/Convolution_Accelerator.runs/impl_1/Conv_Accel_Top_routed.dcp -additional C:/GitHub/ReconHardware/PynqSoftware/Projects/Convolution_Accelerator/Convolution_Accelerator.runs/child_0_impl_1/Conv_Accel_Top_routed.dcp -file child_0_impl_1_pr_verify.log
  open_checkpoint Conv_Accel_Top_routed.dcp
  set_property webtalk.parent_dir C:/GitHub/ReconHardware/PynqSoftware/Projects/Convolution_Accelerator/Convolution_Accelerator.cache/wt [current_project]
  set_property XPM_LIBRARIES XPM_CDC [current_project]
  catch { write_mem_info -force Conv_Accel_Top.mmi }
  write_bitstream -force -no_partial_bitfile Conv_Accel_Top.bit 
  write_bitstream -force -cell ConvAccel/matrixAccel/finalAdder ConvAccel_matrixAccel_finalAdder_adderFloat_partial.bit 
  write_bitstream -force -cell ConvAccel/matrixAccel/genblk3[0].inputMulti ConvAccel_matrixAccel_genblk3_0_.inputMulti_Floating_partial.bit 
  write_bitstream -force -cell ConvAccel/matrixAccel/genblk3[1].inputMulti ConvAccel_matrixAccel_genblk3_1_.inputMulti_Floating_partial.bit 
  write_bitstream -force -cell ConvAccel/matrixAccel/genblk3[2].inputMulti ConvAccel_matrixAccel_genblk3_2_.inputMulti_Floating_partial.bit 
  write_bitstream -force -cell ConvAccel/matrixAccel/genblk4[0].outputAdder ConvAccel_matrixAccel_genblk4_0_.outputAdder_adderFloat_partial.bit 
  write_bitstream -force -cell ConvAccel/matrixAccel/genblk4[1].outputAdder ConvAccel_matrixAccel_genblk4_1_.outputAdder_adderFloat_partial.bit 
  write_bitstream -force -cell ConvAccel/matrixAccel/genblk4[2].outputAdder ConvAccel_matrixAccel_genblk4_2_.outputAdder_adderFloat_partial.bit 
  catch {write_debug_probes -no_partial_ltxfile -quiet -force Conv_Accel_Top}
  catch {file copy -force Conv_Accel_Top.ltx debug_nets.ltx}
  catch {write_debug_probes -quiet -force -cell ConvAccel/matrixAccel/finalAdder -file ConvAccel_matrixAccel_finalAdder_adderFloat_partial.ltx}
  catch {write_debug_probes -quiet -force -cell ConvAccel/matrixAccel/genblk3[0].inputMulti -file ConvAccel_matrixAccel_genblk3_0_.inputMulti_Floating_partial.ltx}
  catch {write_debug_probes -quiet -force -cell ConvAccel/matrixAccel/genblk3[1].inputMulti -file ConvAccel_matrixAccel_genblk3_1_.inputMulti_Floating_partial.ltx}
  catch {write_debug_probes -quiet -force -cell ConvAccel/matrixAccel/genblk3[2].inputMulti -file ConvAccel_matrixAccel_genblk3_2_.inputMulti_Floating_partial.ltx}
  catch {write_debug_probes -quiet -force -cell ConvAccel/matrixAccel/genblk4[0].outputAdder -file ConvAccel_matrixAccel_genblk4_0_.outputAdder_adderFloat_partial.ltx}
  catch {write_debug_probes -quiet -force -cell ConvAccel/matrixAccel/genblk4[1].outputAdder -file ConvAccel_matrixAccel_genblk4_1_.outputAdder_adderFloat_partial.ltx}
  catch {write_debug_probes -quiet -force -cell ConvAccel/matrixAccel/genblk4[2].outputAdder -file ConvAccel_matrixAccel_genblk4_2_.outputAdder_adderFloat_partial.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

