# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/Convolution_Controller_smartconnect_0_1.xci
# IP: The module: 'Convolution_Controller_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/bd_95cb.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_0/bd_95cb_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_1/bd_95cb_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_2/bd_95cb_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_3/bd_95cb_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_4/bd_95cb_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_5/bd_95cb_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_6/bd_95cb_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_7/bd_95cb_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_8/bd_95cb_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_9/bd_95cb_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_10/bd_95cb_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_11/bd_95cb_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_12/bd_95cb_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_13/bd_95cb_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_14/bd_95cb_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_15/bd_95cb_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_16/bd_95cb_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_17/bd_95cb_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_18/bd_95cb_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_19/bd_95cb_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_20/bd_95cb_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_21/bd_95cb_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_22/bd_95cb_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_23/bd_95cb_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_24/bd_95cb_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_25/bd_95cb_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_26/bd_95cb_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_27/bd_95cb_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_28/bd_95cb_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_29/bd_95cb_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_30/bd_95cb_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_31/bd_95cb_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_32/bd_95cb_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_1/bd_95cb_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_1/bd_95cb_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_2/bd_95cb_arsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_3/bd_95cb_rsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_4/bd_95cb_awsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_5/bd_95cb_wsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_6/bd_95cb_bsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_10/bd_95cb_s00a2s_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_11/bd_95cb_sarn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_12/bd_95cb_srn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_16/bd_95cb_s01a2s_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_17/bd_95cb_sawn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_18/bd_95cb_swn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_19/bd_95cb_sbn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_23/bd_95cb_s02a2s_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_24/bd_95cb_sarn_1_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_25/bd_95cb_srn_1_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_26/bd_95cb_m00s2a_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_27/bd_95cb_m00arn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_28/bd_95cb_m00rn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_29/bd_95cb_m00awn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_30/bd_95cb_m00wn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_31/bd_95cb_m00bn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Convolution_Controller_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/Convolution_Controller_smartconnect_0_1.xci
# IP: The module: 'Convolution_Controller_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/bd_95cb.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_0/bd_95cb_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_1/bd_95cb_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_2/bd_95cb_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_3/bd_95cb_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_4/bd_95cb_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_5/bd_95cb_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_6/bd_95cb_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_7/bd_95cb_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_8/bd_95cb_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_9/bd_95cb_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_10/bd_95cb_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_11/bd_95cb_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_12/bd_95cb_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_13/bd_95cb_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_14/bd_95cb_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_15/bd_95cb_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_16/bd_95cb_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_17/bd_95cb_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_18/bd_95cb_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_19/bd_95cb_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_20/bd_95cb_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_21/bd_95cb_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_22/bd_95cb_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_23/bd_95cb_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_24/bd_95cb_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_25/bd_95cb_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_26/bd_95cb_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_27/bd_95cb_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_28/bd_95cb_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_29/bd_95cb_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_30/bd_95cb_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_31/bd_95cb_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_32/bd_95cb_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_1/bd_95cb_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_1/bd_95cb_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_2/bd_95cb_arsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_3/bd_95cb_rsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_4/bd_95cb_awsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_5/bd_95cb_wsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_6/bd_95cb_bsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_10/bd_95cb_s00a2s_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_11/bd_95cb_sarn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_12/bd_95cb_srn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_16/bd_95cb_s01a2s_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_17/bd_95cb_sawn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_18/bd_95cb_swn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_19/bd_95cb_sbn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_23/bd_95cb_s02a2s_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_24/bd_95cb_sarn_1_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_25/bd_95cb_srn_1_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_26/bd_95cb_m00s2a_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_27/bd_95cb_m00arn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_28/bd_95cb_m00rn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_29/bd_95cb_m00awn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_30/bd_95cb_m00wn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/bd_0/ip/ip_31/bd_95cb_m00bn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/ConvolutionAccel_d/ConvolutionAccel_d.srcs/sources_1/bd/Convolution_Controller/ip/Convolution_Controller_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Convolution_Controller_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
