# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/Convolution_Controller.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller || ORIG_REF_NAME==Convolution_Controller} -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_processing_system7_0_1/Convolution_Controller_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_processing_system7_0_1 || ORIG_REF_NAME==Convolution_Controller_processing_system7_0_1} -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_Convolution_Controll_0_1/Convolution_Controller_Convolution_Controll_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_Convolution_Controll_0_1 || ORIG_REF_NAME==Convolution_Controller_Convolution_Controll_0_1} -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_axi_dma_0_1/Convolution_Controller_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_axi_dma_0_1 || ORIG_REF_NAME==Convolution_Controller_axi_dma_0_1} -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_xbar_1/Convolution_Controller_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_xbar_1 || ORIG_REF_NAME==Convolution_Controller_xbar_1} -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_ps7_0_axi_periph_1/Convolution_Controller_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_ps7_0_axi_periph_1 || ORIG_REF_NAME==Convolution_Controller_ps7_0_axi_periph_1} -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_rst_ps7_0_100M_1/Convolution_Controller_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_rst_ps7_0_100M_1 || ORIG_REF_NAME==Convolution_Controller_rst_ps7_0_100M_1} -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_xbar_2/Convolution_Controller_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_xbar_2 || ORIG_REF_NAME==Convolution_Controller_xbar_2} -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_axi_mem_intercon_0/Convolution_Controller_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_axi_mem_intercon_0 || ORIG_REF_NAME==Convolution_Controller_axi_mem_intercon_0} -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_auto_pc_0/Convolution_Controller_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_pc_0 || ORIG_REF_NAME==Convolution_Controller_auto_pc_0} -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_auto_us_0/Convolution_Controller_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_us_0 || ORIG_REF_NAME==Convolution_Controller_auto_us_0} -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_auto_us_1/Convolution_Controller_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_us_1 || ORIG_REF_NAME==Convolution_Controller_auto_us_1} -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_auto_pc_1/Convolution_Controller_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_pc_1 || ORIG_REF_NAME==Convolution_Controller_auto_pc_1} -quiet] -quiet

# XDC: C:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/Convolution_Controller_ooc.xdc
