# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/ps_Wrap/ps_Wrap.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_Wrap || ORIG_REF_NAME==ps_Wrap} -quiet] -quiet

# IP: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/ps_Wrap/ip/ps_Wrap_ParallelBuffer_0_0/ps_Wrap_ParallelBuffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_Wrap_ParallelBuffer_0_0 || ORIG_REF_NAME==ps_Wrap_ParallelBuffer_0_0} -quiet] -quiet

# IP: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/ps_Wrap/ip/ps_Wrap_dataSplit_0_0/ps_Wrap_dataSplit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_Wrap_dataSplit_0_0 || ORIG_REF_NAME==ps_Wrap_dataSplit_0_0} -quiet] -quiet

# Block Designs: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/PYNQ_wrap/PYNQ_wrap.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_wrap || ORIG_REF_NAME==PYNQ_wrap} -quiet] -quiet

# IP: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/PYNQ_wrap/ip/PYNQ_wrap_processing_system7_0_0/PYNQ_wrap_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_wrap_processing_system7_0_0 || ORIG_REF_NAME==PYNQ_wrap_processing_system7_0_0} -quiet] -quiet

# IP: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/PYNQ_wrap/ip/PYNQ_wrap_xlslice_0_3/PYNQ_wrap_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_wrap_xlslice_0_3 || ORIG_REF_NAME==PYNQ_wrap_xlslice_0_3} -quiet] -quiet

# IP: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/PYNQ_wrap/ip/PYNQ_wrap_xlconcat_0_0/PYNQ_wrap_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_wrap_xlconcat_0_0 || ORIG_REF_NAME==PYNQ_wrap_xlconcat_0_0} -quiet] -quiet

# IP: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/PYNQ_wrap/ip/PYNQ_wrap_Clk_0/PYNQ_wrap_Clk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_wrap_Clk_0 || ORIG_REF_NAME==PYNQ_wrap_Clk_0} -quiet] -quiet

# IP: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/PYNQ_wrap/ip/PYNQ_wrap_Rst_1/PYNQ_wrap_Rst_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_wrap_Rst_1 || ORIG_REF_NAME==PYNQ_wrap_Rst_1} -quiet] -quiet

# IP: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/PYNQ_wrap/ip/PYNQ_wrap_dataInput_0/PYNQ_wrap_dataInput_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_wrap_dataInput_0 || ORIG_REF_NAME==PYNQ_wrap_dataInput_0} -quiet] -quiet

# IP: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/PYNQ_wrap/ip/PYNQ_wrap_cStart_0/PYNQ_wrap_cStart_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_wrap_cStart_0 || ORIG_REF_NAME==PYNQ_wrap_cStart_0} -quiet] -quiet

# XDC: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/ps_Wrap/ps_Wrap_ooc.xdc

# XDC: C:/GitHub/ReconHardware/PynqSoftware/Sources/Block Diagrams/PYNQ_wrap/PYNQ_wrap_ooc.xdc
