# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AXI_Invert_Testing/AXI_Invert_Testing.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing || ORIG_REF_NAME==AXI_Invert_Testing} -quiet] -quiet

# IP: bd/AXI_Invert_Testing/ip/AXI_Invert_Testing_processing_system7_0_0/AXI_Invert_Testing_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing_processing_system7_0_0 || ORIG_REF_NAME==AXI_Invert_Testing_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_Invert_Testing/ip/AXI_Invert_Testing_axi_dma_0_0/AXI_Invert_Testing_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing_axi_dma_0_0 || ORIG_REF_NAME==AXI_Invert_Testing_axi_dma_0_0} -quiet] -quiet

# IP: bd/AXI_Invert_Testing/ip/AXI_Invert_Testing_xbar_0/AXI_Invert_Testing_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing_xbar_0 || ORIG_REF_NAME==AXI_Invert_Testing_xbar_0} -quiet] -quiet

# IP: bd/AXI_Invert_Testing/ip/AXI_Invert_Testing_ps7_0_axi_periph_0/AXI_Invert_Testing_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_Invert_Testing_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_Invert_Testing/ip/AXI_Invert_Testing_rst_ps7_0_100M_0/AXI_Invert_Testing_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing_rst_ps7_0_100M_0 || ORIG_REF_NAME==AXI_Invert_Testing_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/AXI_Invert_Testing/ip/AXI_Invert_Testing_Convolution_Controll_0_0/AXI_Invert_Testing_Convolution_Controll_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing_Convolution_Controll_0_0 || ORIG_REF_NAME==AXI_Invert_Testing_Convolution_Controll_0_0} -quiet] -quiet

# IP: bd/AXI_Invert_Testing/ip/AXI_Invert_Testing_xbar_1/AXI_Invert_Testing_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing_xbar_1 || ORIG_REF_NAME==AXI_Invert_Testing_xbar_1} -quiet] -quiet

# IP: bd/AXI_Invert_Testing/ip/AXI_Invert_Testing_axi_mem_intercon_0/AXI_Invert_Testing_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing_axi_mem_intercon_0 || ORIG_REF_NAME==AXI_Invert_Testing_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/AXI_Invert_Testing/ip/AXI_Invert_Testing_auto_pc_0/AXI_Invert_Testing_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing_auto_pc_0 || ORIG_REF_NAME==AXI_Invert_Testing_auto_pc_0} -quiet] -quiet

# IP: bd/AXI_Invert_Testing/ip/AXI_Invert_Testing_auto_us_0/AXI_Invert_Testing_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing_auto_us_0 || ORIG_REF_NAME==AXI_Invert_Testing_auto_us_0} -quiet] -quiet

# IP: bd/AXI_Invert_Testing/ip/AXI_Invert_Testing_auto_us_1/AXI_Invert_Testing_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing_auto_us_1 || ORIG_REF_NAME==AXI_Invert_Testing_auto_us_1} -quiet] -quiet

# IP: bd/AXI_Invert_Testing/ip/AXI_Invert_Testing_auto_pc_1/AXI_Invert_Testing_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_Invert_Testing_auto_pc_1 || ORIG_REF_NAME==AXI_Invert_Testing_auto_pc_1} -quiet] -quiet

# XDC: bd/AXI_Invert_Testing/AXI_Invert_Testing_ooc.xdc
