# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MultiplyBlock_0_0/design_1_MultiplyBlock_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_MultiplyBlock_0_0 || ORIG_REF_NAME==design_1_MultiplyBlock_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dataIn_0/design_1_dataIn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dataIn_0 || ORIG_REF_NAME==design_1_dataIn_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bufferRD_0/design_1_bufferRD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bufferRD_0 || ORIG_REF_NAME==design_1_bufferRD_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bufferWR_0/design_1_bufferWR_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bufferWR_0 || ORIG_REF_NAME==design_1_bufferWR_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bufferEN_0/design_1_bufferEN_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bufferEN_0 || ORIG_REF_NAME==design_1_bufferEN_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bufferEN_1/design_1_bufferEN_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bufferEN_1 || ORIG_REF_NAME==design_1_bufferEN_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mStart_0/design_1_mStart_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mStart_0 || ORIG_REF_NAME==design_1_mStart_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
