# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_0_1/design_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rclk_0/design_2_rclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rclk_0 || ORIG_REF_NAME==design_2_rclk_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rd_0/design_2_rd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rd_0 || ORIG_REF_NAME==design_2_rd_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rrst_0/design_2_rrst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rrst_0 || ORIG_REF_NAME==design_2_rrst_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_wclk_0/design_2_wclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_wclk_0 || ORIG_REF_NAME==design_2_wclk_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_wdata_0/design_2_wdata_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_wdata_0 || ORIG_REF_NAME==design_2_wdata_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_wr_0/design_2_wr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_wr_0 || ORIG_REF_NAME==design_2_wr_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_wrst_0/design_2_wrst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_wrst_0 || ORIG_REF_NAME==design_2_wrst_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconcat_0_0_1/design_2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconcat_0_0 || ORIG_REF_NAME==design_2_xlconcat_0_0} -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
