# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Pixel_Control/Pixel_Control.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control || ORIG_REF_NAME==Pixel_Control} -quiet] -quiet

# IP: bd/Pixel_Control/ip/Pixel_Control_processing_system7_0_0/Pixel_Control_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control_processing_system7_0_0 || ORIG_REF_NAME==Pixel_Control_processing_system7_0_0} -quiet] -quiet

# IP: bd/Pixel_Control/ip/Pixel_Control_axi_dma_0_0/Pixel_Control_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control_axi_dma_0_0 || ORIG_REF_NAME==Pixel_Control_axi_dma_0_0} -quiet] -quiet

# IP: bd/Pixel_Control/ip/Pixel_Control_xbar_1/Pixel_Control_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control_xbar_1 || ORIG_REF_NAME==Pixel_Control_xbar_1} -quiet] -quiet

# IP: bd/Pixel_Control/ip/Pixel_Control_auto_pc_0/Pixel_Control_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control_auto_pc_0 || ORIG_REF_NAME==Pixel_Control_auto_pc_0} -quiet] -quiet

# IP: bd/Pixel_Control/ip/Pixel_Control_ps7_0_axi_periph_0/Pixel_Control_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control_ps7_0_axi_periph_0 || ORIG_REF_NAME==Pixel_Control_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Pixel_Control/ip/Pixel_Control_rst_ps7_0_50M_0/Pixel_Control_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control_rst_ps7_0_50M_0 || ORIG_REF_NAME==Pixel_Control_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Pixel_Control/ip/Pixel_Control_xbar_0/Pixel_Control_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control_xbar_0 || ORIG_REF_NAME==Pixel_Control_xbar_0} -quiet] -quiet

# IP: bd/Pixel_Control/ip/Pixel_Control_auto_us_0/Pixel_Control_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control_auto_us_0 || ORIG_REF_NAME==Pixel_Control_auto_us_0} -quiet] -quiet

# IP: bd/Pixel_Control/ip/Pixel_Control_auto_us_1/Pixel_Control_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control_auto_us_1 || ORIG_REF_NAME==Pixel_Control_auto_us_1} -quiet] -quiet

# IP: bd/Pixel_Control/ip/Pixel_Control_auto_pc_1/Pixel_Control_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control_auto_pc_1 || ORIG_REF_NAME==Pixel_Control_auto_pc_1} -quiet] -quiet

# IP: bd/Pixel_Control/ip/Pixel_Control_axi_mem_intercon_0/Pixel_Control_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control_axi_mem_intercon_0 || ORIG_REF_NAME==Pixel_Control_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/Pixel_Control/ip/Pixel_Control_Pixel_Controller_0_0/Pixel_Control_Pixel_Controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Control_Pixel_Controller_0_0 || ORIG_REF_NAME==Pixel_Control_Pixel_Controller_0_0} -quiet] -quiet

# XDC: bd/Pixel_Control/Pixel_Control_ooc.xdc
