# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ESP32_Map.xdc

# Block Designs: bd/pbuffer_splitter_wrapper/pbuffer_splitter_wrapper.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pbuffer_splitter_wrapper || ORIG_REF_NAME==pbuffer_splitter_wrapper} -quiet] -quiet

# IP: bd/pbuffer_splitter_wrapper/ip/pbuffer_splitter_wrapper_ParallelBuffer_0_0/pbuffer_splitter_wrapper_ParallelBuffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pbuffer_splitter_wrapper_ParallelBuffer_0_0 || ORIG_REF_NAME==pbuffer_splitter_wrapper_ParallelBuffer_0_0} -quiet] -quiet

# IP: bd/pbuffer_splitter_wrapper/ip/pbuffer_splitter_wrapper_dataSplit_0_0/pbuffer_splitter_wrapper_dataSplit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pbuffer_splitter_wrapper_dataSplit_0_0 || ORIG_REF_NAME==pbuffer_splitter_wrapper_dataSplit_0_0} -quiet] -quiet

# XDC: bd/pbuffer_splitter_wrapper/pbuffer_splitter_wrapper_ooc.xdc
