#define TMRCTR_DEVICE_ID  XPAR_TMRCTR_0_DEVICE_ID
#define TIMER_COUNTER_0   0
#define TIMER_COUNTER_1   1

#define PARTIAL_SHIFT_RIGHT_RM_SIZE         (0x7A82C)
#define PARTIAL_SHIFT_LEFT_RM_SIZE          (0x7A82C)
#define PARTIAL_COUNT_UP_RM_SIZE            (0x99D5C)
#define PARTIAL_COUNT_DOWN_RM_SIZE          (0x99D5C)
#define PARTIAL_SHIFT_RIGHT_PFCRC_RM_SIZE   (0x810C0)
#define PARTIAL_SHIFT_LEFT_PFCRC_RM_SIZE    (0x810C0)
#define PARTIAL_COUNT_UP_PFCRC_RM_SIZE      (0xA2098)
#define PARTIAL_COUNT_DOWN_PFCRC_RM_SIZE    (0xA2098)

#define PARTIAL_SHIFT_LEFT_ADDR             (0x0EB7800)
#define PARTIAL_SHIFT_RIGHT_ADDR            (0x0F32400)
#define PARTIAL_COUNT_UP_ADDR               (0x0FAD000)
#define PARTIAL_COUNT_DOWN_ADDR             (0x1047000)
#define PARTIAL_SHIFT_LEFT_PFCRC_ADDR       (0x10E1000)
#define PARTIAL_SHIFT_RIGHT_PFCRC_ADDR      (0x1162400)
#define PARTIAL_COUNT_UP_PFCRC_ADDR         (0x11E3800)
#define PARTIAL_COUNT_DOWN_PFCRC_ADDR       (0x1285C00)
                                             
#define FULL_DATA_SIZE                      PARTIAL_COUNT_DOWN_PFCRC_ADDR+PARTIAL_COUNT_DOWN_PFCRC_RM_SIZE
#define PARTIAL_DATA_SIZE                   FULL_DATA_SIZE-PARTIAL_SHIFT_LEFT_ADDR

#define PARTIAL_SPI_SHIFT_LEFT_ADDR         XPAR_SPI_0_AXI4_BASEADDR+PARTIAL_SHIFT_LEFT_ADDR
#define PARTIAL_SPI_SHIFT_RIGHT_ADDR        XPAR_SPI_0_AXI4_BASEADDR+PARTIAL_SHIFT_RIGHT_ADDR
#define PARTIAL_SPI_COUNT_UP_ADDR           XPAR_SPI_0_AXI4_BASEADDR+PARTIAL_COUNT_UP_ADDR
#define PARTIAL_SPI_COUNT_DOWN_ADDR         XPAR_SPI_0_AXI4_BASEADDR+PARTIAL_COUNT_DOWN_ADDR

#define PARTIAL_SPI_SHIFT_LEFT_PFCRC_ADDR   XPAR_SPI_0_AXI4_BASEADDR+PARTIAL_SHIFT_LEFT_PFCRC_ADDR
#define PARTIAL_SPI_SHIFT_RIGHT_PFCRC_ADDR  XPAR_SPI_0_AXI4_BASEADDR+PARTIAL_SHIFT_RIGHT_PFCRC_ADDR
#define PARTIAL_SPI_COUNT_UP_PFCRC_ADDR     XPAR_SPI_0_AXI4_BASEADDR+PARTIAL_COUNT_UP_PFCRC_ADDR
#define PARTIAL_SPI_COUNT_DOWN_PFCRC_ADDR   XPAR_SPI_0_AXI4_BASEADDR+PARTIAL_COUNT_DOWN_PFCRC_ADDR

#define PARTIAL_DDR_SHIFT_LEFT_ADDR         XPAR_MIG_0_BASEADDR+PARTIAL_SHIFT_LEFT_ADDR
#define PARTIAL_DDR_SHIFT_RIGHT_ADDR        XPAR_MIG_0_BASEADDR+PARTIAL_SHIFT_RIGHT_ADDR
#define PARTIAL_DDR_COUNT_UP_ADDR           XPAR_MIG_0_BASEADDR+PARTIAL_COUNT_UP_ADDR
#define PARTIAL_DDR_COUNT_DOWN_ADDR         XPAR_MIG_0_BASEADDR+PARTIAL_COUNT_DOWN_ADDR

#define PARTIAL_DDR_SHIFT_LEFT_PFCRC_ADDR   XPAR_MIG_0_BASEADDR+PARTIAL_SHIFT_LEFT_PFCRC_ADDR
#define PARTIAL_DDR_SHIFT_RIGHT_PFCRC_ADDR  XPAR_MIG_0_BASEADDR+PARTIAL_SHIFT_RIGHT_PFCRC_ADDR
#define PARTIAL_DDR_COUNT_UP_PFCRC_ADDR     XPAR_MIG_0_BASEADDR+PARTIAL_COUNT_UP_PFCRC_ADDR
#define PARTIAL_DDR_COUNT_DOWN_PFCRC_ADDR   XPAR_MIG_0_BASEADDR+PARTIAL_COUNT_DOWN_PFCRC_ADDR

#define XPRC_DEVICE_ID                      XPAR_HIER_PRC_PRC_0_DEVICE_ID
#define XPRC_VS_SHIFT_ID                    XPAR_HIER_PRC_PRC_0_VS_SHIFT_ID
#define XPRC_VS_COUNT_ID                    XPAR_HIER_PRC_PRC_0_VS_COUNT_ID
#define XPRC_VS_SHIFT_RM_SHIFT_RIGHT_ID     XPAR_HIER_PRC_PRC_0_VS_SHIFT_RM_SHIFT_RIGHT_ID
#define XPRC_VS_SHIFT_RM_SHIFT_LEFT_ID      XPAR_HIER_PRC_PRC_0_VS_SHIFT_RM_SHIFT_LEFT_ID
#define XPRC_VS_COUNT_RM_COUNT_UP_ID        XPAR_HIER_PRC_PRC_0_VS_COUNT_RM_COUNT_UP_ID
#define XPRC_VS_COUNT_RM_COUNT_DOWN_ID      XPAR_HIER_PRC_PRC_0_VS_COUNT_RM_COUNT_DOWN_ID
