# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_processing_system7_0_1/Convolution_Controller_processing_system7_0_1.xci
# IP: The module: 'Convolution_Controller_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_processing_system7_0_1/Convolution_Controller_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Convolution_Controller_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_processing_system7_0_1/Convolution_Controller_processing_system7_0_1.xci
# IP: The module: 'Convolution_Controller_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Sources/Block Diagrams/Convolution_Controller/ip/Convolution_Controller_processing_system7_0_1/Convolution_Controller_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Convolution_Controller_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
