# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects_Testing/PR_LED/PR_LED.srcs/sources_1/bd/PR_LED_des/ip/PR_LED_des_processing_system7_0_0/PR_LED_des_processing_system7_0_0.xci
# IP: The module: 'PR_LED_des_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects_Testing/PR_LED/PR_LED.srcs/sources_1/bd/PR_LED_des/ip/PR_LED_des_processing_system7_0_0/PR_LED_des_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PR_LED_des_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects_Testing/PR_LED/PR_LED.srcs/sources_1/bd/PR_LED_des/ip/PR_LED_des_processing_system7_0_0/PR_LED_des_processing_system7_0_0.xci
# IP: The module: 'PR_LED_des_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects_Testing/PR_LED/PR_LED.srcs/sources_1/bd/PR_LED_des/ip/PR_LED_des_processing_system7_0_0/PR_LED_des_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PR_LED_des_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
