# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/buttonMap.xdc

# Block Designs: bd/io_switch/io_switch.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==io_switch || ORIG_REF_NAME==io_switch} -quiet] -quiet

# IP: bd/io_switch/ip/io_switch_inputOutput_0_0/io_switch_inputOutput_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==io_switch_inputOutput_0_0 || ORIG_REF_NAME==io_switch_inputOutput_0_0} -quiet] -quiet

# XDC: bd/io_switch/io_switch_ooc.xdc
