set_property SRC_FILE_INFO {cfile:C:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.srcs/constrs_1/new/mybrd.xdc rfile:../../../CONV_ULTRA.srcs/constrs_1/new/mybrd.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B4 [get_ports {led[0]}]
