set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TKEEP[1]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TKEEP[0]}]
set_property MARK_DEBUG true [get_nets BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TLAST]
set_property MARK_DEBUG true [get_nets BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TVALID]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TKEEP[2]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TKEEP[3]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[31]}]
set_property MARK_DEBUG true [get_nets BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TREADY]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[0]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[1]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[6]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[13]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[14]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[18]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[20]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[23]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[24]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[29]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[25]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[2]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[10]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[16]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[17]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[19]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[22]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[27]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[28]}]
set_property MARK_DEBUG true [get_nets BD_Wrapper/Convolution_Controller_i/cReady_0]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[3]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[4]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[7]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[12]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[21]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[26]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[31]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[5]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[8]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[9]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[11]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[15]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/cSum_0[30]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TKEEP[1]}]
set_property MARK_DEBUG true [get_nets BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TVALID]
set_property MARK_DEBUG true [get_nets BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TREADY]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TKEEP[0]}]
set_property MARK_DEBUG true [get_nets BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TLAST]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TKEEP[3]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TKEEP[2]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list BD_Wrapper/Convolution_Controller_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[0]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[1]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[2]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[3]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[4]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[5]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[6]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[7]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[8]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[9]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[10]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[11]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[12]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[13]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[14]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[15]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[16]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[17]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[18]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[19]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[20]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[21]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[22]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[23]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[24]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[25]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[26]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[27]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[28]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[29]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[30]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TKEEP[0]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TKEEP[1]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TKEEP[2]} {BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TKEEP[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TKEEP[0]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TKEEP[1]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TKEEP[2]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TKEEP[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[0]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[1]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[2]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[3]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[4]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[5]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[6]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[7]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[8]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[9]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[10]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[11]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[12]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[13]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[14]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[15]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[16]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[17]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[18]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[19]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[20]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[21]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[22]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[23]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[24]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[25]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[26]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[27]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[28]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[29]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[30]} {BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {BD_Wrapper/Convolution_Controller_i/cSum_0[0]} {BD_Wrapper/Convolution_Controller_i/cSum_0[1]} {BD_Wrapper/Convolution_Controller_i/cSum_0[2]} {BD_Wrapper/Convolution_Controller_i/cSum_0[3]} {BD_Wrapper/Convolution_Controller_i/cSum_0[4]} {BD_Wrapper/Convolution_Controller_i/cSum_0[5]} {BD_Wrapper/Convolution_Controller_i/cSum_0[6]} {BD_Wrapper/Convolution_Controller_i/cSum_0[7]} {BD_Wrapper/Convolution_Controller_i/cSum_0[8]} {BD_Wrapper/Convolution_Controller_i/cSum_0[9]} {BD_Wrapper/Convolution_Controller_i/cSum_0[10]} {BD_Wrapper/Convolution_Controller_i/cSum_0[11]} {BD_Wrapper/Convolution_Controller_i/cSum_0[12]} {BD_Wrapper/Convolution_Controller_i/cSum_0[13]} {BD_Wrapper/Convolution_Controller_i/cSum_0[14]} {BD_Wrapper/Convolution_Controller_i/cSum_0[15]} {BD_Wrapper/Convolution_Controller_i/cSum_0[16]} {BD_Wrapper/Convolution_Controller_i/cSum_0[17]} {BD_Wrapper/Convolution_Controller_i/cSum_0[18]} {BD_Wrapper/Convolution_Controller_i/cSum_0[19]} {BD_Wrapper/Convolution_Controller_i/cSum_0[20]} {BD_Wrapper/Convolution_Controller_i/cSum_0[21]} {BD_Wrapper/Convolution_Controller_i/cSum_0[22]} {BD_Wrapper/Convolution_Controller_i/cSum_0[23]} {BD_Wrapper/Convolution_Controller_i/cSum_0[24]} {BD_Wrapper/Convolution_Controller_i/cSum_0[25]} {BD_Wrapper/Convolution_Controller_i/cSum_0[26]} {BD_Wrapper/Convolution_Controller_i/cSum_0[27]} {BD_Wrapper/Convolution_Controller_i/cSum_0[28]} {BD_Wrapper/Convolution_Controller_i/cSum_0[29]} {BD_Wrapper/Convolution_Controller_i/cSum_0[30]} {BD_Wrapper/Convolution_Controller_i/cSum_0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list BD_Wrapper/Convolution_Controller_i/axi_dma_0_M_AXIS_MM2S_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list BD_Wrapper/Convolution_Controller_i/Convolution_Controll_0_m_axis_DATA_OUT_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list BD_Wrapper/Convolution_Controller_i/cReady_0]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
