# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bram_ila/bram_ila.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_ila || ORIG_REF_NAME==bram_ila} -quiet] -quiet

# IP: bd/bram_ila/ip/bram_ila_ila_0_0/bram_ila_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_ila_ila_0_0 || ORIG_REF_NAME==bram_ila_ila_0_0} -quiet] -quiet

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_dma_0_0 || ORIG_REF_NAME==design_2_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_ps7_0_100M_0/design_2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_smartconnect_0_0/design_2_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_smartconnect_0_0 || ORIG_REF_NAME==design_2_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_smartconnect_0_1/design_2_smartconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_smartconnect_0_1 || ORIG_REF_NAME==design_2_smartconnect_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_1/design_2_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_1 || ORIG_REF_NAME==design_2_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ila_0_0/design_2_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ila_0_0 || ORIG_REF_NAME==design_2_ila_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ila_0_1/design_2_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ila_0_1 || ORIG_REF_NAME==design_2_ila_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ila_1_0/design_2_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ila_1_0 || ORIG_REF_NAME==design_2_ila_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ila_0_2/design_2_ila_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ila_0_2 || ORIG_REF_NAME==design_2_ila_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ila_0_3/design_2_ila_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ila_0_3 || ORIG_REF_NAME==design_2_ila_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ila_0_4/design_2_ila_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ila_0_4 || ORIG_REF_NAME==design_2_ila_0_4} -quiet] -quiet

# XDC: bd/bram_ila/bram_ila_ooc.xdc

# XDC: bd/design_2/design_2_ooc.xdc
