# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/resizer/resizer.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer || ORIG_REF_NAME==resizer} -quiet] -quiet

# IP: bd/resizer/ip/resizer_axi_dma_0_0/resizer_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_axi_dma_0_0 || ORIG_REF_NAME==resizer_axi_dma_0_0} -quiet] -quiet

# IP: bd/resizer/ip/resizer_axi_interconnect_0_0/resizer_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_axi_interconnect_0_0 || ORIG_REF_NAME==resizer_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/resizer/ip/resizer_axi_interconnect_1_0/resizer_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_axi_interconnect_1_0 || ORIG_REF_NAME==resizer_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/resizer/ip/resizer_axis_dwidth_converter_0_0/resizer_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_axis_dwidth_converter_0_0 || ORIG_REF_NAME==resizer_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/resizer/ip/resizer_axis_dwidth_converter_1_0/resizer_axis_dwidth_converter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_axis_dwidth_converter_1_0 || ORIG_REF_NAME==resizer_axis_dwidth_converter_1_0} -quiet] -quiet

# IP: bd/resizer/ip/resizer_processing_system7_0_0/resizer_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_processing_system7_0_0 || ORIG_REF_NAME==resizer_processing_system7_0_0} -quiet] -quiet

# IP: bd/resizer/ip/resizer_resize_accel_0_0/resizer_resize_accel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_resize_accel_0_0 || ORIG_REF_NAME==resizer_resize_accel_0_0} -quiet] -quiet

# IP: bd/resizer/ip/resizer_rst_ps7_0_100M_0/resizer_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_rst_ps7_0_100M_0 || ORIG_REF_NAME==resizer_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/resizer/ip/resizer_xbar_2/resizer_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_xbar_2 || ORIG_REF_NAME==resizer_xbar_2} -quiet] -quiet

# IP: bd/resizer/ip/resizer_xbar_3/resizer_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_xbar_3 || ORIG_REF_NAME==resizer_xbar_3} -quiet] -quiet

# IP: bd/resizer/ip/resizer_auto_pc_0/resizer_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_auto_pc_0 || ORIG_REF_NAME==resizer_auto_pc_0} -quiet] -quiet

# IP: bd/resizer/ip/resizer_auto_us_0/resizer_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_auto_us_0 || ORIG_REF_NAME==resizer_auto_us_0} -quiet] -quiet

# IP: bd/resizer/ip/resizer_auto_us_1/resizer_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_auto_us_1 || ORIG_REF_NAME==resizer_auto_us_1} -quiet] -quiet

# IP: bd/resizer/ip/resizer_auto_pc_1/resizer_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==resizer_auto_pc_1 || ORIG_REF_NAME==resizer_auto_pc_1} -quiet] -quiet

# XDC: bd/resizer/resizer_ooc.xdc
