# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/monke/Downloads/imageFilterIP-master/imageFilterIP-master/dma_handle/dma_handle.srcs/sources_1/bd/dma_FIFO/ip/dma_FIFO_axi_dma_0_0/dma_FIFO_axi_dma_0_0.xci
# IP: The module: 'dma_FIFO_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/monke/Downloads/imageFilterIP-master/imageFilterIP-master/dma_handle/dma_handle.srcs/sources_1/bd/dma_FIFO/ip/dma_FIFO_axi_dma_0_0/dma_FIFO_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_FIFO_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/monke/Downloads/imageFilterIP-master/imageFilterIP-master/dma_handle/dma_handle.srcs/sources_1/bd/dma_FIFO/ip/dma_FIFO_axi_dma_0_0/dma_FIFO_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_FIFO_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/monke/Downloads/imageFilterIP-master/imageFilterIP-master/dma_handle/dma_handle.srcs/sources_1/bd/dma_FIFO/ip/dma_FIFO_axi_dma_0_0/dma_FIFO_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_FIFO_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/monke/Downloads/imageFilterIP-master/imageFilterIP-master/dma_handle/dma_handle.srcs/sources_1/bd/dma_FIFO/ip/dma_FIFO_axi_dma_0_0/dma_FIFO_axi_dma_0_0.xci
# IP: The module: 'dma_FIFO_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/monke/Downloads/imageFilterIP-master/imageFilterIP-master/dma_handle/dma_handle.srcs/sources_1/bd/dma_FIFO/ip/dma_FIFO_axi_dma_0_0/dma_FIFO_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_FIFO_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/monke/Downloads/imageFilterIP-master/imageFilterIP-master/dma_handle/dma_handle.srcs/sources_1/bd/dma_FIFO/ip/dma_FIFO_axi_dma_0_0/dma_FIFO_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_FIFO_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/monke/Downloads/imageFilterIP-master/imageFilterIP-master/dma_handle/dma_handle.srcs/sources_1/bd/dma_FIFO/ip/dma_FIFO_axi_dma_0_0/dma_FIFO_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_FIFO_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
