# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
create_project -in_memory -part xczu3eg-sbva484-1-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.cache/wt [current_project]
set_property parent.project_path C:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:ultra96v2:part0:1.0 [current_project]
set_property ip_output_repo c:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/GitHub/ReconHardware/PynqSoftware/Sources/definitions.h
set_property file_type "Verilog Header" [get_files C:/GitHub/ReconHardware/PynqSoftware/Sources/definitions.h]
read_verilog -library xil_defaultlib {
  C:/GitHub/ReconHardware/PynqSoftware/Sources/General/XBar2.v
  C:/GitHub/ReconHardware/PynqSoftware/Sources/General/aFIFO.v
  C:/GitHub/ReconHardware/PynqSoftware/Sources/Adder/adder.v
  C:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.srcs/sources_1/bd/design_2/hdl/design_2_wrapper.v
  C:/GitHub/ReconHardware/PynqSoftware/Sources/General/matrixAccTopDevice.v
  C:/GitHub/ReconHardware/PynqSoftware/Sources/General/matrixAccelerator.v
  C:/GitHub/ReconHardware/PynqSoftware/Sources/General/matrixControl3x3.v
  C:/GitHub/ReconHardware/PynqSoftware/Sources/Multiplier/multiplyComputePynq.v
  C:/GitHub/ReconHardware/PynqSoftware/Sources/General/Conv_Accel_Top.v
}
add_files C:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.srcs/sources_1/bd/design_2/design_2.bd
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.srcs/sources_1/bd/design_2/ip/design_2_zynq_ultra_ps_e_0_0/design_2_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.srcs/sources_1/bd/design_2/ip/design_2_zynq_ultra_ps_e_0_0/design_2_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.srcs/sources_1/bd/design_2/design_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.srcs/constrs_1/new/mybrd.xdc
set_property used_in_implementation false [get_files C:/GitHub/ReconHardware/PynqSoftware/Projects/CONV_ULTRA/CONV_ULTRA.srcs/constrs_1/new/mybrd.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Conv_Accel_Top -part xczu3eg-sbva484-1-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Conv_Accel_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Conv_Accel_Top_utilization_synth.rpt -pb Conv_Accel_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
