# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mybrd.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Rst_0/design_2_Rst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_Rst_0 || ORIG_REF_NAME==design_2_Rst_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_bufferInput_0/design_2_bufferInput_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_bufferInput_0 || ORIG_REF_NAME==design_2_bufferInput_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_cStart_0/design_2_cStart_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_cStart_0 || ORIG_REF_NAME==design_2_cStart_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_io_clk_0/design_2_io_clk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_io_clk_0 || ORIG_REF_NAME==design_2_io_clk_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_newline_0/design_2_newline_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_newline_0 || ORIG_REF_NAME==design_2_newline_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rd_0/design_2_rd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rd_0 || ORIG_REF_NAME==design_2_rd_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_wr_0/design_2_wr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_wr_0 || ORIG_REF_NAME==design_2_wr_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconcat_0_0/design_2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconcat_0_0 || ORIG_REF_NAME==design_2_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_zynq_ultra_ps_e_0_0/design_2_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_2_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_1 || ORIG_REF_NAME==design_2_clk_wiz_0_1} -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
