# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.runs/system_axi_smc_2_synth_1/system_axi_smc_2.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "system_axi_smc_2_synth_1" START { ROLLUP_AUTO }
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.cache/wt [current_project]
set_property parent.project_path C:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/ipcores [current_project]
update_ip_catalog
set_property ip_output_repo d:/VivadoProject/PRwithZycap/imageProcessingVideoDisplay.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_ip -quiet C:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2.xci
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_1/bd_8562_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_1/bd_8562_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_2/bd_8562_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_3/bd_8562_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_4/bd_8562_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_5/bd_8562_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_6/bd_8562_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_7/bd_8562_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_8/bd_8562_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_9/bd_8562_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_10/bd_8562_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_11/bd_8562_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_12/bd_8562_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_13/bd_8562_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_14/bd_8562_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_15/bd_8562_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_16/bd_8562_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_20/bd_8562_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_21/bd_8562_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_22/bd_8562_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_23/bd_8562_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_24/bd_8562_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_25/bd_8562_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_26/bd_8562_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_27/bd_8562_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_28/bd_8562_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_29/bd_8562_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_30/bd_8562_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_31/bd_8562_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_33/bd_8562_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_34/bd_8562_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_35/bd_8562_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_36/bd_8562_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_37/bd_8562_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_38/bd_8562_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_40/bd_8562_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_41/bd_8562_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_42/bd_8562_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_43/bd_8562_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_44/bd_8562_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_45/bd_8562_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
OPTRACE "Configure IP Cache" START { }

set cached_ip [config_ip_cache -export -no_bom  -dir C:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.runs/system_axi_smc_2_synth_1 -new_name system_axi_smc_2 -ip [get_ips system_axi_smc_2]]

OPTRACE "Configure IP Cache" END { }
if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top system_axi_smc_2 -part xc7z020clg400-1 -mode out_of_context
OPTRACE "synth_design" END { }
OPTRACE "Write IP Cache" START { }

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix system_axi_smc_2_ system_axi_smc_2.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_axi_smc_2_stub.v
 lappend ipCachedFiles system_axi_smc_2_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_axi_smc_2_stub.vhdl
 lappend ipCachedFiles system_axi_smc_2_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_axi_smc_2_sim_netlist.v
 lappend ipCachedFiles system_axi_smc_2_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_axi_smc_2_sim_netlist.vhdl
 lappend ipCachedFiles system_axi_smc_2_sim_netlist.vhdl
 set TIME_taken [expr [clock seconds] - $TIME_start]

 if { [get_msg_config -count -severity {CRITICAL WARNING}] == 0 } {
  config_ip_cache -add -dcp system_axi_smc_2.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips system_axi_smc_2]
 }
OPTRACE "Write IP Cache" END { }
}

rename_ref -prefix_all system_axi_smc_2_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_axi_smc_2.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "system_axi_smc_2_synth_1_synth_report_utilization_0" "report_utilization -file system_axi_smc_2_utilization_synth.rpt -pb system_axi_smc_2_utilization_synth.pb"
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force C:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.runs/system_axi_smc_2_synth_1/system_axi_smc_2.dcp c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.runs/system_axi_smc_2_synth_1/system_axi_smc_2.dcp c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.runs/system_axi_smc_2_synth_1/system_axi_smc_2_stub.v c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.runs/system_axi_smc_2_synth_1/system_axi_smc_2_stub.vhdl c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.runs/system_axi_smc_2_synth_1/system_axi_smc_2_sim_netlist.v c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.runs/system_axi_smc_2_synth_1/system_axi_smc_2_sim_netlist.vhdl c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir D:/VivadoProject/PRwithZycap/imageProcessingVideoDisplay.ip_user_files/ip/system_axi_smc_2]} {
  catch { 
    file copy -force c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2_stub.v D:/VivadoProject/PRwithZycap/imageProcessingVideoDisplay.ip_user_files/ip/system_axi_smc_2
  }
}

if {[file isdir D:/VivadoProject/PRwithZycap/imageProcessingVideoDisplay.ip_user_files/ip/system_axi_smc_2]} {
  catch { 
    file copy -force c:/GitHub/ReconHardware/FPGA_Files/Projects/PRwithZycap/imageProcessingVideoDisplay.srcs/sources_1/bd/system/ip/system_axi_smc_2/system_axi_smc_2_stub.vhdl D:/VivadoProject/PRwithZycap/imageProcessingVideoDisplay.ip_user_files/ip/system_axi_smc_2
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "system_axi_smc_2_synth_1" END { }
