# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_pr_4_decoupler_0/prio_pr_4_decoupler_0.xci
# IP: The module: 'prio_pr_4_decoupler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_pr_4_decoupler_0/prio_pr_4_decoupler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prio_pr_4_decoupler_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_pr_4_decoupler_0/prio_pr_4_decoupler_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'prio_pr_4_decoupler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_pr_4_decoupler_0/prio_pr_4_decoupler_0.xci
# IP: The module: 'prio_pr_4_decoupler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_pr_4_decoupler_0/prio_pr_4_decoupler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prio_pr_4_decoupler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/monke/Downloads/PYNQ-PRIO-master/PYNQ-PRIO-master/boards/Pynq-Z1/prio/prio/prio.srcs/sources_1/bd/prio/ip/prio_pr_4_decoupler_0/prio_pr_4_decoupler_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'prio_pr_4_decoupler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
