# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Convolution_Controller/Convolution_Controller.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller || ORIG_REF_NAME==Convolution_Controller} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_processing_system7_0_0/Convolution_Controller_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_processing_system7_0_0 || ORIG_REF_NAME==Convolution_Controller_processing_system7_0_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_axi_dma_0_1/Convolution_Controller_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_axi_dma_0_1 || ORIG_REF_NAME==Convolution_Controller_axi_dma_0_1} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_ps7_0_axi_periph_0/Convolution_Controller_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_ps7_0_axi_periph_0 || ORIG_REF_NAME==Convolution_Controller_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_rst_ps7_0_100M_0/Convolution_Controller_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_rst_ps7_0_100M_0 || ORIG_REF_NAME==Convolution_Controller_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_Convolution_Controll_0_1/Convolution_Controller_Convolution_Controll_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_Convolution_Controll_0_1 || ORIG_REF_NAME==Convolution_Controller_Convolution_Controll_0_1} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_Convolution_Controll_0_bram_2/Convolution_Controller_Convolution_Controll_0_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_Convolution_Controll_0_bram_2 || ORIG_REF_NAME==Convolution_Controller_Convolution_Controll_0_bram_2} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_axi_mem_intercon_1/Convolution_Controller_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_axi_mem_intercon_1 || ORIG_REF_NAME==Convolution_Controller_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_Convolution_Controll_0_bram_3/Convolution_Controller_Convolution_Controll_0_bram_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_Convolution_Controll_0_bram_3 || ORIG_REF_NAME==Convolution_Controller_Convolution_Controll_0_bram_3} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_Convolution_Controll_0_bram_4/Convolution_Controller_Convolution_Controll_0_bram_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_Convolution_Controll_0_bram_4 || ORIG_REF_NAME==Convolution_Controller_Convolution_Controll_0_bram_4} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_dfx_controller_0_0_1/Convolution_Controller_dfx_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_dfx_controller_0_0 || ORIG_REF_NAME==Convolution_Controller_dfx_controller_0_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_dfx_decoupler_0_0_1/Convolution_Controller_dfx_decoupler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_dfx_decoupler_0_0 || ORIG_REF_NAME==Convolution_Controller_dfx_decoupler_0_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_xbar_1/Convolution_Controller_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_xbar_1 || ORIG_REF_NAME==Convolution_Controller_xbar_1} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_xbar_0/Convolution_Controller_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_xbar_0 || ORIG_REF_NAME==Convolution_Controller_xbar_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_dfx_decoupler_0_1_1/Convolution_Controller_dfx_decoupler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_dfx_decoupler_0_1 || ORIG_REF_NAME==Convolution_Controller_dfx_decoupler_0_1} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_util_vector_logic_0_0_1/Convolution_Controller_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_util_vector_logic_0_0 || ORIG_REF_NAME==Convolution_Controller_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_auto_pc_0/Convolution_Controller_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_pc_0 || ORIG_REF_NAME==Convolution_Controller_auto_pc_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_auto_us_0/Convolution_Controller_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_us_0 || ORIG_REF_NAME==Convolution_Controller_auto_us_0} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_auto_us_1/Convolution_Controller_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_us_1 || ORIG_REF_NAME==Convolution_Controller_auto_us_1} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_auto_us_2/Convolution_Controller_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_us_2 || ORIG_REF_NAME==Convolution_Controller_auto_us_2} -quiet] -quiet

# IP: bd/Convolution_Controller/ip/Convolution_Controller_auto_pc_1/Convolution_Controller_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Convolution_Controller_auto_pc_1 || ORIG_REF_NAME==Convolution_Controller_auto_pc_1} -quiet] -quiet

# XDC: bd/Convolution_Controller/Convolution_Controller_ooc.xdc
