# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CPE/Projects/pooling_layer/pooling_layer.srcs/sources_1/bd/design_1/ip/design_1_Pooling_Controller_0_0/design_1_Pooling_Controller_0_0.xci
# IP: The module: 'design_1_Pooling_Controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CPE/Projects/pooling_layer/pooling_layer.srcs/sources_1/bd/design_1/ip/design_1_Pooling_Controller_0_0/src/BRAM/ip/BRAM_blk_mem_gen_0_0/BRAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==BRAM_blk_mem_gen_0_0} -quiet] -quiet

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CPE/Projects/pooling_layer/pooling_layer.srcs/sources_1/bd/design_1/ip/design_1_Pooling_Controller_0_0/src/BRAM/ip/BRAM_blk_mem_gen_0_0/BRAM_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CPE/Projects/pooling_layer/pooling_layer.srcs/sources_1/bd/design_1/ip/design_1_Pooling_Controller_0_0/src/BRAM/BRAM_ooc.xdc

# IP: c:/GitHub/ReconHardware/FPGA_Files/CPE/Projects/pooling_layer/pooling_layer.srcs/sources_1/bd/design_1/ip/design_1_Pooling_Controller_0_0/design_1_Pooling_Controller_0_0.xci
# IP: The module: 'design_1_Pooling_Controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CPE/Projects/pooling_layer/pooling_layer.srcs/sources_1/bd/design_1/ip/design_1_Pooling_Controller_0_0/src/BRAM/ip/BRAM_blk_mem_gen_0_0/BRAM_blk_mem_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==BRAM_blk_mem_gen_0_0} -quiet] -quiet

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CPE/Projects/pooling_layer/pooling_layer.srcs/sources_1/bd/design_1/ip/design_1_Pooling_Controller_0_0/src/BRAM/ip/BRAM_blk_mem_gen_0_0/BRAM_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CPE/Projects/pooling_layer/pooling_layer.srcs/sources_1/bd/design_1/ip/design_1_Pooling_Controller_0_0/src/BRAM/BRAM_ooc.xdc
