set_property PACKAGE_PIN R14 [get_ports {flatOutput[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutput[0]}]

set_property PACKAGE_PIN P14 [get_ports {flatOutput[1]}]
set_property PACKAGE_PIN N16 [get_ports {flatOutput[2]}]
set_property PACKAGE_PIN M14 [get_ports {flatOutput[3]}]
set_property PACKAGE_PIN L15 [get_ports {flatOutput[4]}]
set_property PACKAGE_PIN N15 [get_ports {flatOutput[5]}]
set_property PACKAGE_PIN G17 [get_ports {flatOutput[6]}]
set_property PACKAGE_PIN G14 [get_ports {flatOutput[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {button[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[0]}]
set_property PACKAGE_PIN D19 [get_ports {button[0]}]
set_property PACKAGE_PIN D20 [get_ports {button[1]}]
set_property PACKAGE_PIN L20 [get_ports {button[2]}]
set_property PACKAGE_PIN L19 [get_ports {button[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {AddressSelect[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AddressSelect[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatInputPort[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatInputPort[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatInputPort[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatInputPort[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutputPort[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutputPort[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutputPort[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flatOutputPort[0]}]
set_property PACKAGE_PIN A20 [get_ports Rst]
set_property PULLDOWN true [get_ports Rst]
set_property PACKAGE_PIN M19 [get_ports direct]
set_property PACKAGE_PIN M20 [get_ports ]
set_property PACKAGE_PIN R14 [get_ports {flatOutputPort[0]}]
set_property PACKAGE_PIN P14 [get_ports {flatOutputPort[1]}]
set_property PACKAGE_PIN M14 [get_ports {flatOutputPort[3]}]
set_property PACKAGE_PIN N16 [get_ports {flatOutputPort[2]}]
set_property PACKAGE_PIN L19 [get_ports {flatInputPort[3]}]
set_property PACKAGE_PIN L20 [get_ports {flatInputPort[2]}]
set_property PACKAGE_PIN D20 [get_ports {flatInputPort[1]}]
set_property PACKAGE_PIN D19 [get_ports {flatInputPort[0]}]
set_property PACKAGE_PIN B19 [get_ports {AddressSelect[1]}]
set_property PACKAGE_PIN B20 [get_ports {AddressSelect[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports direct]
set_property IOSTANDARD LVCMOS33 [get_ports Rst]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets MyInput_IBUF]

set_property PACKAGE_PIN M20 [get_ports MyInput]
set_property IOSTANDARD LVCMOS33 [get_ports MyInput]
