# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/FIFO_Stream/FIFO_Stream.srcs/sources_1/bd/FIFO_Stream/ip/FIFO_Stream_axi_dma_0_0/FIFO_Stream_axi_dma_0_0.xci
# IP: The module: 'FIFO_Stream_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/FIFO_Stream/FIFO_Stream.srcs/sources_1/bd/FIFO_Stream/ip/FIFO_Stream_axi_dma_0_0/FIFO_Stream_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_Stream_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/FIFO_Stream/FIFO_Stream.srcs/sources_1/bd/FIFO_Stream/ip/FIFO_Stream_axi_dma_0_0/FIFO_Stream_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_Stream_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/FIFO_Stream/FIFO_Stream.srcs/sources_1/bd/FIFO_Stream/ip/FIFO_Stream_axi_dma_0_0/FIFO_Stream_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_Stream_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects/FIFO_Stream/FIFO_Stream.srcs/sources_1/bd/FIFO_Stream/ip/FIFO_Stream_axi_dma_0_0/FIFO_Stream_axi_dma_0_0.xci
# IP: The module: 'FIFO_Stream_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/FIFO_Stream/FIFO_Stream.srcs/sources_1/bd/FIFO_Stream/ip/FIFO_Stream_axi_dma_0_0/FIFO_Stream_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_Stream_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/FIFO_Stream/FIFO_Stream.srcs/sources_1/bd/FIFO_Stream/ip/FIFO_Stream_axi_dma_0_0/FIFO_Stream_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_Stream_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects/FIFO_Stream/FIFO_Stream.srcs/sources_1/bd/FIFO_Stream/ip/FIFO_Stream_axi_dma_0_0/FIFO_Stream_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_Stream_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
