# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Pixel_Controller_ILA/Pixel_Controller_ILA.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA || ORIG_REF_NAME==Pixel_Controller_ILA} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_Pixel_Controller_0_0/Pixel_Controller_ILA_Pixel_Controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_Pixel_Controller_0_0 || ORIG_REF_NAME==Pixel_Controller_ILA_Pixel_Controller_0_0} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_axi_dma_0_0/Pixel_Controller_ILA_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_axi_dma_0_0 || ORIG_REF_NAME==Pixel_Controller_ILA_axi_dma_0_0} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_xbar_0/Pixel_Controller_ILA_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_xbar_0 || ORIG_REF_NAME==Pixel_Controller_ILA_xbar_0} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_axi_mem_intercon_0/Pixel_Controller_ILA_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_axi_mem_intercon_0 || ORIG_REF_NAME==Pixel_Controller_ILA_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_processing_system7_0_0/Pixel_Controller_ILA_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_processing_system7_0_0 || ORIG_REF_NAME==Pixel_Controller_ILA_processing_system7_0_0} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_xbar_1/Pixel_Controller_ILA_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_xbar_1 || ORIG_REF_NAME==Pixel_Controller_ILA_xbar_1} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_ps7_0_axi_periph_0/Pixel_Controller_ILA_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_ps7_0_axi_periph_0 || ORIG_REF_NAME==Pixel_Controller_ILA_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_rst_ps7_0_100M_0/Pixel_Controller_ILA_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_rst_ps7_0_100M_0 || ORIG_REF_NAME==Pixel_Controller_ILA_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_ila_0_0/Pixel_Controller_ILA_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_ila_0_0 || ORIG_REF_NAME==Pixel_Controller_ILA_ila_0_0} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_ila_0_3/Pixel_Controller_ILA_ila_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_ila_0_3 || ORIG_REF_NAME==Pixel_Controller_ILA_ila_0_3} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_ila_1_0/Pixel_Controller_ILA_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_ila_1_0 || ORIG_REF_NAME==Pixel_Controller_ILA_ila_1_0} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_auto_us_0/Pixel_Controller_ILA_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_auto_us_0 || ORIG_REF_NAME==Pixel_Controller_ILA_auto_us_0} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_auto_us_1/Pixel_Controller_ILA_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_auto_us_1 || ORIG_REF_NAME==Pixel_Controller_ILA_auto_us_1} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_auto_pc_0/Pixel_Controller_ILA_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_auto_pc_0 || ORIG_REF_NAME==Pixel_Controller_ILA_auto_pc_0} -quiet] -quiet

# IP: bd/Pixel_Controller_ILA/ip/Pixel_Controller_ILA_auto_pc_1/Pixel_Controller_ILA_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_ILA_auto_pc_1 || ORIG_REF_NAME==Pixel_Controller_ILA_auto_pc_1} -quiet] -quiet

# XDC: bd/Pixel_Controller_ILA/Pixel_Controller_ILA_ooc.xdc
