# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Pixel_Controller_BD/Pixel_Controller_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD || ORIG_REF_NAME==Pixel_Controller_BD} -quiet] -quiet

# IP: bd/Pixel_Controller_BD/ip/Pixel_Controller_BD_processing_system7_0_0/Pixel_Controller_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD_processing_system7_0_0 || ORIG_REF_NAME==Pixel_Controller_BD_processing_system7_0_0} -quiet] -quiet

# IP: bd/Pixel_Controller_BD/ip/Pixel_Controller_BD_axi_dma_0_0/Pixel_Controller_BD_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD_axi_dma_0_0 || ORIG_REF_NAME==Pixel_Controller_BD_axi_dma_0_0} -quiet] -quiet

# IP: bd/Pixel_Controller_BD/ip/Pixel_Controller_BD_Pixel_Controller_0_0/Pixel_Controller_BD_Pixel_Controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD_Pixel_Controller_0_0 || ORIG_REF_NAME==Pixel_Controller_BD_Pixel_Controller_0_0} -quiet] -quiet

# IP: bd/Pixel_Controller_BD/ip/Pixel_Controller_BD_xbar_0/Pixel_Controller_BD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD_xbar_0 || ORIG_REF_NAME==Pixel_Controller_BD_xbar_0} -quiet] -quiet

# IP: bd/Pixel_Controller_BD/ip/Pixel_Controller_BD_ps7_0_axi_periph_0/Pixel_Controller_BD_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD_ps7_0_axi_periph_0 || ORIG_REF_NAME==Pixel_Controller_BD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Pixel_Controller_BD/ip/Pixel_Controller_BD_rst_ps7_0_100M_0/Pixel_Controller_BD_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD_rst_ps7_0_100M_0 || ORIG_REF_NAME==Pixel_Controller_BD_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Pixel_Controller_BD/ip/Pixel_Controller_BD_xbar_1/Pixel_Controller_BD_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD_xbar_1 || ORIG_REF_NAME==Pixel_Controller_BD_xbar_1} -quiet] -quiet

# IP: bd/Pixel_Controller_BD/ip/Pixel_Controller_BD_axi_mem_intercon_0/Pixel_Controller_BD_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD_axi_mem_intercon_0 || ORIG_REF_NAME==Pixel_Controller_BD_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/Pixel_Controller_BD/ip/Pixel_Controller_BD_auto_pc_0/Pixel_Controller_BD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD_auto_pc_0 || ORIG_REF_NAME==Pixel_Controller_BD_auto_pc_0} -quiet] -quiet

# IP: bd/Pixel_Controller_BD/ip/Pixel_Controller_BD_auto_us_0/Pixel_Controller_BD_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD_auto_us_0 || ORIG_REF_NAME==Pixel_Controller_BD_auto_us_0} -quiet] -quiet

# IP: bd/Pixel_Controller_BD/ip/Pixel_Controller_BD_auto_us_1/Pixel_Controller_BD_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD_auto_us_1 || ORIG_REF_NAME==Pixel_Controller_BD_auto_us_1} -quiet] -quiet

# IP: bd/Pixel_Controller_BD/ip/Pixel_Controller_BD_auto_pc_1/Pixel_Controller_BD_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pixel_Controller_BD_auto_pc_1 || ORIG_REF_NAME==Pixel_Controller_BD_auto_pc_1} -quiet] -quiet

# XDC: bd/Pixel_Controller_BD/Pixel_Controller_BD_ooc.xdc
