# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects_Testing/FIFO_stream/FIFO_stream.srcs/sources_1/bd/dmaFIFO/ip/dmaFIFO_xbar_1/dmaFIFO_xbar_1.xci
# IP: The module: 'dmaFIFO_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects_Testing/FIFO_stream/FIFO_stream.srcs/sources_1/bd/dmaFIFO/ip/dmaFIFO_xbar_1/dmaFIFO_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaFIFO_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/Projects_Testing/FIFO_stream/FIFO_stream.srcs/sources_1/bd/dmaFIFO/ip/dmaFIFO_xbar_1/dmaFIFO_xbar_1.xci
# IP: The module: 'dmaFIFO_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/Projects_Testing/FIFO_stream/FIFO_stream.srcs/sources_1/bd/dmaFIFO/ip/dmaFIFO_xbar_1/dmaFIFO_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaFIFO_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
