# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/PynqSoftware/pynq-z2_v1.0.xdc

# Block Designs: bd/buffer_splitter_wrapper/buffer_splitter_wrapper.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buffer_splitter_wrapper || ORIG_REF_NAME==buffer_splitter_wrapper} -quiet] -quiet

# IP: bd/buffer_splitter_wrapper/ip/buffer_splitter_wrapper_dataSplit_0_0/buffer_splitter_wrapper_dataSplit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buffer_splitter_wrapper_dataSplit_0_0 || ORIG_REF_NAME==buffer_splitter_wrapper_dataSplit_0_0} -quiet] -quiet

# IP: bd/buffer_splitter_wrapper/ip/buffer_splitter_wrapper_ParallelBuffer_0_0/buffer_splitter_wrapper_ParallelBuffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buffer_splitter_wrapper_ParallelBuffer_0_0 || ORIG_REF_NAME==buffer_splitter_wrapper_ParallelBuffer_0_0} -quiet] -quiet

# XDC: bd/buffer_splitter_wrapper/buffer_splitter_wrapper_ooc.xdc
