# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
# IP: The module: 'design_1_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/bd_48ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_48ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sarn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_srn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sawn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_swn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sbn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_m00s2a_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_m00arn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_m00rn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_m00awn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00wn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00bn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_m01s2a_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_m01arn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_m01rn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m01awn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m01wn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m01bn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
# IP: The module: 'design_1_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/bd_48ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_48ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sarn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_srn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sawn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_swn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sbn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_m00s2a_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_m00arn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_m00rn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_m00awn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00wn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00bn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_m01s2a_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_m01arn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_m01rn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m01awn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m01wn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m01bn_0_ooc.xdc

# XDC: c:/GitHub/ReconHardware/FPGA_Files/CNN/Projects/conv_layer/conv_layer.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
